Config = {}

Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)
Config.PauseMapText = 'Boardwalk RP'                         -- Text shown above the map when ESC is pressed. If left empty 'FiveM' will appear
Config.HarnessUses = 20
Config.DamageNeeded = 100.0                                  -- amount of damage till you can push your vehicle. 0-1000

Config.AFK = {
    ignoredGroups = {
        ['mod'] = true,
        ['admin'] = true,
        ['god'] = true
    },
    secondsUntilKick = 1000000, -- AFK Kick Time Limit (in seconds)
    kickInCharMenu = false      -- Set to true if you want to kick players for being AFK even when they are in the character menu.
}

Config.HandsUp = {
    command = 'hu',
    keybind = 'X',
    controls = { 24, 25, 47, 58, 59, 63, 64, 71, 72, 75, 140, 141, 142, 143, 257, 263, 264 }
}

Config.Binoculars = {
    zoomSpeed = 10.0,        -- camera zoom speed
    storeBinocularsKey = 177 -- backspace by default
}

Config.AIResponse = {
    wantedLevels = false, -- if true, you will recieve wanted levels
    dispatchServices = {  -- AI dispatch services
        [1] = false,      -- Police Vehicles
        [2] = false,      -- Police Helicopters
        [3] = false,      -- Fire Department Vehicles
        [4] = false,      -- Swat Vehicles
        [5] = false,      -- Ambulance Vehicles
        [6] = false,      -- Police Motorcycles
        [7] = false,      -- Police Backup
        [8] = false,      -- Police Roadblocks
        [9] = false,      -- PoliceAutomobileWaitPulledOver
        [10] = false,     -- PoliceAutomobileWaitCruising
        [11] = false,     -- Gang Members
        [12] = false,     -- Swat Helicopters
        [13] = false,     -- Police Boats
        [14] = false,     -- Army Vehicles
        [15] = false      -- Biker Backup
    }
}

-- To Set This Up visit https://forum.cfx.re/t/how-to-updated-discord-rich-presence-custom-image/157686
Config.Discord = {
    isEnabled = true,                                      -- If set to true, then discord rich presence will be enabled
    applicationId = '1084538529645858856',                 -- The discord application id
    iconLarge = 'boardwalklarge',                          -- The name of the large icon
    iconLargeHoverText = 'Boardwalk RP',                   -- The hover text of the large icon
    iconSmall = 'small_logo_name',                         -- The name of the small icon
    iconSmallHoverText = 'This is a Small icon with text', -- The hover text of the small icon
    updateRate = 60000,                                    -- How often the player count should be updated
    showPlayerCount = true,                                -- If set to true the player count will be displayed in the rich presence
    maxPlayers = 48,                                       -- Maximum amount of players
    buttons = {
        {
            text = 'Join our Discord!',
            url = 'https://discord.gg/vrUHgMWN'
        },
    }
}

Config.Density = {
    parked = 1.0,
    vehicle = 1.0,
    multiplier = 1.0,
    peds = 1.0,
    scenario = 1.0,
}

Config.Disable = {
    hudComponents = { 1, 2, 3, 4, 7, 9, 13, 19, 20, 21, 22 }, -- Hud Components: https://docs.fivem.net/natives/?_0x6806C51AD12B83B8
    controls = { 37 },                                            -- Controls: https://docs.fivem.net/docs/game-references/controls/
    displayAmmo = true,                                           -- false disables ammo display
    ambience = true,                                              -- disables distance sirens, distance car alarms, flight music, etc
    idleCamera = true,                                            -- disables the idle cinematic camera
    vestDrawable = false,                                         -- disables the vest equipped when using heavy armor
    pistolWhipping = true,                                        -- disables pistol whipping
    driveby = false,                                              -- disables driveby
}

Config.WhitelistedReticleWeapons = {
    `weapon_sniperrifle`,
    `weapon_heavysniper`,
    `weapon_marksmanrifle`,
    `weapon_remotesniper`,
    `weapon_heavysniper_mk2`,
    `weapon_marksmanrifle_mk2`,
    `weapon_spring`,
}

Config.Consumables = {
    eat = { -- default food items
        ['friedcatfish'] = math.random(60, 80),
        ['potpie'] = math.random(60, 80),
        ['friedchicken'] = math.random(60, 80),
        ['biscuitsandgravy'] = math.random(60, 80),
        ['breakfast'] = math.random(60, 80),
        ['frenchtoast'] = math.random(60, 80),
        ['cologreens'] = math.random(60, 80),
        ['cornbread'] = math.random(60, 80),
        ['pickledpig'] = math.random(60, 80),
        ['turkeyneck'] = math.random(60, 80),
        ['redcake'] = math.random(60, 80),
        ['coleslaw'] = math.random(60, 80),
        ['macaroni'] = math.random(60, 80),
        ['okonomiyaki'] = math.random(60, 80),
        ['tonkatsu'] = math.random(60, 80),
        ['miso'] = math.random(60, 80),
        ['hotdog'] = math.random(60, 80),
        ['pretzel'] = math.random(60, 80),
        ['nachosb'] = math.random(60, 80),
        ['psteak'] = math.random(60, 80),
        ['goulash'] = math.random(60, 80),
        ['schnitzel'] = math.random(60, 80),
        ['frenchfries'] = math.random(60, 80),
        ['hamburger'] = math.random(60, 80),
        ['cheeseburger'] = math.random(60, 80),
        ['doubledouble'] = math.random(60, 80),
        ['pt_tiramisu'] = math.random(60, 80),
        ['pt_icecream'] = math.random(60, 80),
        ['pt_fruits'] = math.random(60, 80),
        ['taco'] = math.random(30, 50),
        ['burrito'] = math.random(60, 80),
        ['chili_corn_soup'] = math.random(40, 60),
        ['mex_chicken'] = math.random(60, 80),
    },
    drink = { -- default drink items
        ['io_cola'] = math.random(60, 80),
        ['io_icedtea'] = math.random(60, 80),
        ['io_sprunk'] = math.random(60, 80),
        ['io_milkshakev'] = math.random(60, 80),
        ['io_milkshakec'] = math.random(60, 80),
        ['io_milkshakes'] = math.random(60, 80),
        ['orangejuice'] = math.random(60, 80),
        ['milk'] = math.random(60, 80),
        ['water_stolen'] = math.random(90, 100),
        ['kurkastolen'] = math.random(90, 100),
    },
    alcohol = { -- default alcohol items
        ['whiskey'] = math.random(20, 30),
        ['beer'] = math.random(30, 40),
        ['vodka'] = math.random(20, 40),
        ['wine'] = math.random(40, 60),
        ['sake1'] = math.random(60, 80),
        ['shirleytemple'] = math.random(60, 80),
        ['beer_stolen'] = math.random(90, 100),
        ['wine_stolen'] = math.random(90, 100),
    },
    custom = { -- put any custom items here
        -- ['newitem'] = {
        --     progress = {
        --         label = 'Using Item...',
        --         time = 5000
        --     },
        --     animation = {
        --         animDict = 'amb@prop_human_bbq@male@base',
        --         anim = 'base',
        --         flags = 8,
        --     },
        --     prop = {
        --         model = false,
        --         bone = false,
        --         coords = false, -- vector 3 format
        --         rotation = false, -- vector 3 format
        --     },
        --     replenish = {'''
        --         type = 'Hunger', -- replenish type 'Hunger'/'Thirst' / false
        --         replenish = math.random(20, 40),
        --         isAlcohol = false, -- if you want it to add alcohol count
        --         event = false, -- 'eventname' if you want it to trigger an outside event on use useful for drugs
        --         server = false -- if the event above is a server event
        --     }
        -- }
    }
}

Config.Fireworks = {
    delay = 5, -- time in s till it goes off
    items = {  -- firework items
        'firework1',
        'firework2',
        'firework3',
        'firework4'
    }
}

Config.BlacklistedScenarios = {
    types = {
        'WORLD_VEHICLE_MILITARY_PLANES_SMALL',
        'WORLD_VEHICLE_MILITARY_PLANES_BIG',
        'WORLD_VEHICLE_AMBULANCE',
        'WORLD_VEHICLE_POLICE_NEXT_TO_CAR',
        'WORLD_VEHICLE_POLICE_CAR',
        'WORLD_VEHICLE_POLICE_BIKE'
    },
    groups = {
        2017590552,
        2141866469,
        1409640232,
        `ng_planes`
    }
}

Config.BlacklistedVehs = {
    [`adder`] = true,
    [`airbus`] = false,
    [`airtug`] = false,
    [`akula`] = true,
    [`akuma`] = false,
    [`alkonost`] = true,
    [`alpha`] = true,
    [`alphaz1`] = false,
    [`ambulance`] = false,
    [`annihilator`] = true,
    [`annihilator2`] = true,
    [`apc`] = true,
    [`ardent`] = true,
    [`armytanker`] = false,
    [`armytrailer`] = false,
    [`armytrailer2`] = false,
    [`asbo`] = true,
    [`asea`] = true,
    [`asea2`] = true,
    [`asterope`] = true,
    [`astron`] = true,
    [`autarch`] = true,
    [`avarus`] = false,
    [`avenger`] = false,
    [`avenger2`] = true,
    [`avisa`] = true,
    [`bagger`] = false,
    [`baletrailer`] = false,
    [`baller`] = true,
    [`baller2`] = true,
    [`baller3`] = true,
    [`baller4`] = true,
    [`baller5`] = true,
    [`baller6`] = true,
    [`baller7`] = true,
    [`banshee`] = true,
    [`banshee2`] = true,
    [`barracks`] = false,
    [`barracks2`] = false,
    [`barracks3`] = false,
    [`barrage`] = true,
    [`bati`] = false,
    [`bati2`] = false,
    [`benson`] = false,
    [`besra`] = false,
    [`bestiagts`] = true,
    [`bf400`] = true,
    [`bfinjection`] = false,
    [`biff`] = false,
    [`bifta`] = false,
    [`bison`] = true,
    [`bison2`] = true,
    [`bison3`] = true,
    [`bjxl`] = true,
    [`blade`] = false,
    [`blazer`] = false,
    [`blazer2`] = false,
    [`blazer3`] = true,
    [`blazer4`] = true,
    [`blazer5`] = true,
    [`blimp`] = true,
    [`blimp2`] = true,
    [`blimp3`] = true,
    [`blista`] = true,
    [`blista2`] = false,
    [`blista3`] = false,
    [`bmx`] = false,
    [`boattrailer`] = false,
    [`bobcatxl`] = true,
    [`bodhi2`] = false,
    [`bombushka`] = true,
    [`boor`] = false,
    [`boxville`] = false,
    [`boxville2`] = false,
    [`boxville3`] = false,
    [`boxville4`] = false,
    [`boxville5`] = false,
    [`brawler`] = true,
    [`broadway`] = false,
    [`brickade`] = true,
    [`brickade2`] = true,
    ['brigham'] = false,
    [`brioso`] = true,
    [`brioso2`] = false,
    [`brioso3`] = false,
    [`bruiser`] = true,
    [`bruiser2`] = true,
    [`bruiser3`] = true,
    [`brutus`] = true,
    [`brutus2`] = true,
    [`brutus3`] = true,
    [`btype`] = false,
    [`btype2`] = true,
    [`btype3`] = false,
    [`buccaneer`] = false,
    [`buccaneer2`] = false,
    [`buffalo`] = true,
    [`buffalo2`] = true,
    [`buffalo3`] = true,
    [`buffalo4`] = true,
    [`buffalo5`] = true,
    [`bulldozer`] = false,
    [`bullet`] = true,
    [`burrito`] = false,
    [`burrito2`] = false,
    [`burrito3`] = false,
    [`burrito4`] = false,
    [`burrito5`] = false,
    [`bus`] = false,
    [`buzzard`] = true,
    [`buzzard2`] = true,
    [`cablecar`] = true,
    [`caddy`] = false,
    [`caddy2`] = false,
    [`caddy3`] = false,
    [`calico`] = true,
    [`camper`] = false,
    [`caracara`] = true,
    [`caracara2`] = true,
    [`carbonizzare`] = true,
    [`carbonrs`] = false,
    [`cargobob`] = false,
    [`cargobob2`] = false,
    [`cargobob3`] = false,
    [`cargobob4`] = false,
    [`cargoplane`] = true,
    [`cargoplane2`] = true,
    [`casco`] = false,
    [`cavalcade`] = false,
    [`cavalcade2`] = false,
    [`cerberus`] = true,
    [`cerberus2`] = true,
    [`cerberus3`] = true,
    [`champion`] = true,
    [`cheburek`] = false,
    [`cheetah`] = true,
    [`cheetah2`] = false,
    [`chernobog`] = true,
    [`chimera`] = false,
    [`chino`] = false,
    [`chino2`] = false,
    [`cinquemila`] = true,
    [`cliffhanger`] = false,
    [`clique`] = false,
    [`clique2`] = false,
    [`club`] = false,
    [`coach`] = false,
    [`cog55`] = true,
    [`cog552`] = true,
    [`cogcabrio`] = true,
    [`cognoscenti`] = true,
    [`cognoscenti2`] = true,
    [`comet2`] = true,
    [`comet3`] = false,
    [`comet4`] = false,
    [`comet5`] = true,
    [`comet6`] = true,
    [`comet7`] = true,
    [`conada`] = true,
    [`conada2`] = true,
    [`contender`] = true,
    [`coquette`] = true,
    [`coquette2`] = false,
    [`coquette3`] = false,
    [`coquette4`] = true,
    [`coureur`] = true,
    [`corsita`] = true,
    [`cruiser`] = false,
    [`crusader`] = true,
    [`cuban800`] = false,
    [`cutter`] = false,
    [`cyclone`] = true,
    [`cypher`] = true,
    [`daemon`] = false,
    [`daemon2`] = false,
    [`deathbike`] = false,
    [`deathbike2`] = true,
    [`deathbike3`] = true,
    [`defiler`] = true,
    [`deity`] = true,
    [`deluxo`] = true,
    [`deveste`] = true,
    [`deviant`] = true,
    [`diablous`] = true,
    [`diablous2`] = false,
    [`dilettante`] = true,
    [`dilettante2`] = true,
    [`dinghy`] = false,
    [`dinghy2`] = false,
    [`dinghy3`] = false,
    [`dinghy4`] = true,
    [`dinghy5`] = true,
    [`dloader`] = false,
    [`docktrailer`] = false,
    [`docktug`] = false,
    [`dodo`] = false,
    [`dominator`] = true,
    [`dominator2`] = true,
    [`dominator3`] = true,
    [`dominator4`] = true,
    [`dominator5`] = true,
    [`dominator6`] = true,
    [`dominator7`] = true,
    [`dominator8`] = false,
    [`double`] = false,
    [`drafter`] = true,
    [`draugur`] = true,
    [`dubsta`] = true,
    [`dubsta2`] = true,
    [`dubsta3`] = true,
    [`dukes`] = false,
    [`dukes2`] = true,
    [`dukes3`] = false,
    [`dump`] = true,
    [`dune`] = false,
    [`dune2`] = true,
    [`dune3`] = true,
    [`dune4`] = true,
    [`dune5`] = true,
    [`duster`] = false,
    [`dynasty`] = false,
    [`elegy`] = true,
    [`elegy2`] = true,
    [`ellie`] = false,
    [`emerus`] = true,
    [`emperor`] = false,
    [`emperor2`] = false,
    [`emperor3`] = true,
    [`enduro`] = false,
    [`entity2`] = true,
    [`entity3`] = true,
    [`entityxf`] = true,
    [`esskey`] = false,
    [`eudora`] = false,
    [`euros`] = true,
    [`everon`] = true,
    [`everon2`] = true,
    [`exemplar`] = true,
    [`f620`] = true,
    [`faction`] = false,
    [`faction2`] = false,
    [`faction3`] = true,
    [`fagaloa`] = false,
    [`faggio`] = false,
    [`faggio2`] = false,
    [`faggio3`] = false,
    [`fbi`] = true,
    [`fbi2`] = true,
    [`fcr`] = false,
    [`fcr2`] = false,
    [`felon`] = true,
    [`felon2`] = true,
    [`feltzer2`] = true,
    [`feltzer3`] = false,
    [`firetruk`] = true,
    [`fixter`] = false,
    [`flashgt`] = true,
    [`flatbed`] = true,
    [`fmj`] = true,
    [`forklift`] = false,
    [`formula`] = false,
    [`formula2`] = true,
    [`fq2`] = true,
    [`freecrawler`] = true,
    [`freight`] = false,
    [`freightcar`] = false,
    [`freightcar2`] = false,
    [`freightcont1`] = false,
    [`freightcont2`] = false,
    [`freightgrain`] = false,
    [`freighttrailer`] = false,
    [`frogger`] = true,
    [`frogger2`] = true,
    [`fugitive`] = true,
    [`furia`] = true,
    [`furoregt`] = true,
    [`fusilade`] = true,
    [`futo`] = false,
    [`futo2`] = false,
    [`gargoyle`] = false,
    [`gauntlet`] = true,
    [`gauntlet2`] = true,
    [`gauntlet3`] = false,
    [`gauntlet4`] = true,
    [`gauntlet5`] = false,
    [`gauntlet6`] = true,
    [`gb200`] = true,
    [`gburrito`] = true,
    [`gburrito2`] = true,
    [`glendale`] = false,
    [`glendale2`] = false,
    [`gp1`] = true,
    [`graintrailer`] = false,
    [`granger`] = true,
    [`granger2`] = true,
    [`greenwood`] = false,
    [`gresley`] = true,
    [`growler`] = true,
    [`gt500`] = false,
    [`guardian`] = true,
    [`habanero`] = true,
    [`hakuchou`] = true,
    [`hakuchou2`] = true,
    [`halftrack`] = true,
    [`handler`] = false,
    [`hauler`] = false,
    [`hauler2`] = true,
    [`havok`] = true,
    [`hellion`] = true,
    [`hermes`] = false,
    [`hexer`] = false,
    [`hotknife`] = false,
    [`hotring`] = true,
    [`howard`] = false,
    [`hunter`] = false,
    [`huntley`] = true,
    [`hustler`] = false,
    [`hydra`] = true,
    [`ignus`] = true,
    [`imorgon`] = true,
    [`impaler`] = false,
    [`impaler2`] = true,
    [`impaler3`] = true,
    [`impaler4`] = true,
    [`imperator`] = false,
    [`imperator2`] = true,
    [`imperator3`] = true,
    [`infernus`] = true,
    [`infernus2`] = true,
    [`ingot`] = true,
    [`innovation`] = false,
    [`insurgent`] = true,
    [`insurgent2`] = true,
    [`insurgent3`] = true,
    [`intruder`] = true,
    [`issi2`] = true,
    [`issi3`] = false,
    [`issi4`] = true,
    [`issi5`] = true,
    [`issi6`] = true,
    [`issi7`] = true,
    [`issi8`] = true,
    [`italigtb`] = true,
    [`italigtb2`] = true,
    [`italigto`] = true,
    [`italirsx`] = true,
    [`iwagen`] = true,
    [`jackal`] = true,
    [`jb700`] = true,
    [`jb7002`] = false,
    [`jester`] = true,
    [`jester2`] = true,
    [`jester3`] = true,
    [`jester4`] = true,
    [`jet`] = false,
    [`jetmax`] = false,
    [`journey`] = false,
    [`journey2`] = false,
    [`jubilee`] = true,
    [`jugular`] = true,
    [`kalahari`] = false,
    [`kamacho`] = true,
    [`kanjo`] = true,
    [`kanjosj`] = true,
    [`khamelion`] = true,
    [`khanjali`] = true,
    [`komoda`] = true,
    [`kosatka`] = true,
    [`krieger`] = true,
    [`kuruma`] = true,
    [`kuruma2`] = true,
    ['l35'] = false,
    [`landstalker`] = true,
    [`landstalker2`] = true,
    [`lazer`] = true,
    [`le7b`] = true,
    [`lectro`] = true,
    [`lguard`] = true,
    [`limo2`] = true,
    [`lm87`] = true,
    [`locust`] = true,
    [`longfin`] = false,
    [`lurcher`] = true,
    [`luxor`] = true,
    [`luxor2`] = true,
    [`lynx`] = true,
    [`mamba`] = false,
    [`mammatus`] = false,
    [`manana`] = false,
    [`manana2`] = false,
    [`manchez`] = false,
    [`manchez2`] = false,
    [`manchez3`] = false,
    [`marquis`] = false,
    [`marshall`] = true,
    [`massacro`] = true,
    [`massacro2`] = true,
    [`maverick`] = false,
    [`menacer`] = true,
    [`mesa`] = false,
    [`mesa2`] = true,
    [`mesa3`] = true,
    [`metrotrain`] = false,
    [`michelli`] = false,
    [`microlight`] = false,
    [`miljet`] = false,
    [`minitank`] = true,
    [`minivan`] = true,
    [`minivan2`] = true,
    [`mixer`] = false,
    [`mixer2`] = false,
    [`mogul`] = false,
    [`molotok`] = true,
    [`monroe`] = false,
    [`monster`] = true,
    [`monster3`] = true,
    [`monster4`] = true,
    [`monster5`] = true,
    ['monstrociti'] = true,
    [`moonbeam`] = true,
    [`moonbeam2`] = true,
    [`mower`] = false,
    [`mule`] = false,
    [`mule2`] = false,
    [`mule3`] = false,
    [`mule4`] = false,
    [`mule5`] = false,
    [`nebula`] = false,
    [`nemesis`] = true,
    [`neo`] = true,
    [`neon`] = true,
    [`nero`] = true,
    [`nero2`] = true,
    [`nightblade`] = true,
    [`nightshade`] = false,
    [`nightshark`] = true,
    [`nimbus`] = false,
    [`ninef`] = true,
    [`ninef2`] = true,
    [`nokota`] = true,
    [`novak`] = true,
    [`omnis`] = false,
    [`omnisegt`] = true,
    [`openwheel1`] = false,
    [`openwheel2`] = true,
    [`oppressor`] = true,
    [`oppressor2`] = true,
    [`oracle`] = true,
    [`oracle2`] = true,
    [`osiris`] = true,
    [`outlaw`] = true,
    [`packer`] = true,
    [`panthere`] = true,
    [`panto`] = true,
    [`paradise`] = true,
    [`paragon`] = true,
    [`paragon2`] = true,
    [`pariah`] = true,
    [`patriot`] = true,
    [`patriot2`] = true,
    [`patriot3`] = true,
    [`patrolboat`] = true,
    [`pbus`] = false,
    [`pbus2`] = true,
    [`pcj`] = false,
    [`penetrator`] = true,
    [`penumbra`] = true,
    [`penumbra2`] = true,
    [`peyote`] = false,
    [`peyote2`] = false,
    [`peyote3`] = false,
    [`pfister811`] = true,
    [`phantom`] = false,
    [`phantom2`] = true,
    [`phantom3`] = false,
    [`phoenix`] = false,
    [`picador`] = false,
    [`pigalle`] = false,
    [`police`] = true,
    [`police2`] = true,
    [`police3`] = true,
    [`police4`] = true,
    [`policeb`] = false,
    [`policeold1`] = true,
    [`policeold2`] = true,
    [`policet`] = true,
    [`polmav`] = false,
    [`pony`] = true,
    [`pony2`] = true,
    [`powersurge`] = true,
    [`postlude`] = false,
    [`pounder`] = true,
    [`pounder2`] = true,
    [`prairie`] = true,
    [`pranger`] = true,
    [`predator`] = false,
    [`premier`] = true,
    [`previon`] = true,
    [`primo`] = true,
    [`primo2`] = true,
    [`proptrailer`] = true,
    [`prototipo`] = true,
    [`pyro`] = true,
    [`r300`] = true,
    [`radi`] = true,
    [`raiden`] = true,
    [`raketrailer`] = false,
    [`rallytruck`] = true,
    [`rancherxl`] = false,
    [`rancherxl2`] = true,
    [`rapidgt`] = true,
    [`rapidgt2`] = true,
    [`rapidgt3`] = false,
    [`raptor`] = true,
    [`ratbike`] = false,
    [`ratloader`] = false,
    [`ratloader2`] = false,
    [`rcbandito`] = true,
    [`reaper`] = true,
    [`rebel`] = false,
    [`rebel2`] = false,
    [`rebla`] = true,
    [`reever`] = true,
    [`regina`] = false,
    [`remus`] = false,
    [`rentalbus`] = true,
    [`retinue`] = false,
    [`retinue2`] = false,
    [`revolter`] = true,
    [`rhapsody`] = false,
    [`rhinehart`] = true,
    [`rhino`] = true,
    [`riata`] = true,
    [`riot`] = true,
    [`riot2`] = true,
    [`ripley`] = true,
    [`rocoto`] = true,
    [`rogue`] = false,
    [`romero`] = true,
    [`rrocket`] = true,
    [`rt3000`] = true,
    [`rubble`] = false,
    [`ruffian`] = false,
    [`ruiner`] = false,
    [`ruiner2`] = true,
    [`ruiner3`] = false,
    [`ruiner4`] = true,
    [`rumpo`] = true,
    [`rumpo2`] = true,
    [`rumpo3`] = true,
    [`ruston`] = true,
    [`s80`] = true,
    [`sabregt`] = false,
    [`sabregt2`] = false,
    [`sadler`] = true,
    [`sadler2`] = true,
    [`sanchez`] = false,
    [`sanchez2`] = false,
    [`sanctus`] = true,
    [`sandking`] = true,
    [`sandking2`] = true,
    [`savage`] = true,
    [`savestra`] = false,
    [`sc1`] = true,
    [`scarab`] = true,
    [`scarab2`] = true,
    [`scarab3`] = true,
    [`schafter2`] = true,
    [`schafter3`] = true,
    [`schafter4`] = true,
    [`schafter5`] = true,
    [`schafter6`] = true,
    [`schlagen`] = true,
    [`schwarzer`] = true,
    [`scorcher`] = false,
    [`scramjet`] = true,
    [`scrap`] = false,
    [`seabreeze`] = false,
    [`seashark`] = false,
    [`seashark2`] = false,
    [`seashark3`] = false,
    [`seasparrow`] = false,
    [`seasparrow2`] = false,
    [`seasparrow3`] = true,
    [`seminole`] = true,
    [`seminole2`] = false,
    [`sentinel`] = true,
    [`sentinel2`] = true,
    [`sentinel3`] = false,
    [`sentinel4`] = false,
    [`serrano`] = true,
    [`seven70`] = true,
    [`shamal`] = false,
    [`sheava`] = true,
    [`sheriff`] = true,
    [`sheriff2`] = true,
    [`shinobi`] = false,
    [`shotaro`] = true,
    [`skylift`] = true,
    [`slamtruck`] = false,
    [`slamvan`] = false,
    [`slamvan2`] = false,
    [`slamvan3`] = true,
    [`slamvan4`] = true,
    [`slamvan5`] = true,
    [`slamvan6`] = true,
    [`sm722`] = true,
    [`sovereign`] = false,
    [`specter`] = true,
    [`specter2`] = true,
    [`speeder`] = false,
    [`speeder2`] = false,
    [`speedo`] = false,
    [`speedo2`] = true,
    [`speedo4`] = false,
    [`speedo5`] = false,
    [`squaddie`] = false,
    [`squalo`] = false,
    [`stafford`] = false,
    [`stalion`] = false,
    [`stalion2`] = false,
    [`stanier`] = true,
    [`starling`] = true,
    [`stinger`] = false,
    [`stingergt`] = false,
    [`stingertt`] = true,
    [`stockade`] = false,
    [`stockade3`] = true,
    [`stratum`] = true,
    [`streiter`] = true,
    [`stretch`] = true,
    [`strikeforce`] = false,
    [`stromberg`] = true,
    [`stryder`] = true,
    [`stunt`] = false,
    [`submersible`] = true,
    [`submersible2`] = true,
    [`sugoi`] = true,
    [`sultan`] = true,
    [`sultan2`] = true,
    [`sultan3`] = true,
    [`sultanrs`] = true,
    [`suntrap`] = false,
    [`superd`] = true,
    [`supervolito`] = true,
    [`supervolito2`] = true,
    [`surano`] = true,
    [`surfer`] = false,
    [`surfer2`] = false,
    [`surfer3`] = false,
    [`surge`] = true,
    [`swift`] = false,
    [`swift2`] = false,
    [`swinger`] = false,
    [`t20`] = true,
    [`taco`] = false,
    [`tahoma`] = false,
    [`tailgater`] = true,
    [`tailgater2`] = true,
    [`taipan`] = true,
    [`tampa`] = false,
    [`tampa2`] = true,
    [`tampa3`] = true,
    [`tanker`] = false,
    [`tanker2`] = false,
    [`tankercar`] = false,
    [`taxi`] = false,
    [`technical`] = true,
    [`technical2`] = true,
    [`technical3`] = true,
    [`tempesta`] = true,
    [`tenf`] = true,
    [`tenf2`] = true,
    [`terbyte`] = true,
    [`tezeract`] = true,
    [`thrax`] = true,
    [`thrust`] = true,
    [`thruster`] = true,
    [`tigon`] = true,
    [`tiptruck`] = true,
    [`tiptruck2`] = false,
    [`titan`] = false,
    [`toreador`] = true,
    [`torero`] = false,
    [`torero2`] = true,
    [`tornado`] = false,
    [`tornado2`] = false,
    [`tornado3`] = false,
    [`tornado4`] = false,
    [`tornado5`] = false,
    [`tornado6`] = false,
    [`toro`] = false,
    [`toro2`] = false,
    [`toros`] = true,
    [`tourbus`] = true,
    [`towtruck`] = false,
    [`towtruck2`] = false,
    [`tr2`] = false,
    [`tr3`] = false,
    [`tr4`] = true,
    [`tractor`] = false,
    [`tractor2`] = false,
    [`tractor3`] = true,
    [`trailerlarge`] = false,
    [`trailerlogs`] = false,
    [`trailers`] = false,
    [`trailers2`] = false,
    [`trailers3`] = false,
    [`trailers4`] = false,
    [`trailersmall`] = false,
    [`trailersmall2`] = false,
    [`trash`] = false,
    [`trash2`] = false,
    [`trflat`] = false,
    [`tribike`] = false,
    [`tribike2`] = false,
    [`tribike3`] = false,
    [`trophytruck`] = true,
    [`trophytruck2`] = true,
    [`tropic`] = false,
    [`tropic2`] = false,
    [`tropos`] = false,
    [`tug`] = false,
    [`tula`] = true,
    [`tulip`] = false,
    [`tulip2`] = false,
    [`turismo2`] = false,
    [`turismor`] = true,
    [`tvtrailer`] = true,
    [`tyrant`] = true,
    [`tyrus`] = true,
    [`utillitruck`] = false,
    [`utillitruck2`] = false,
    [`utillitruck3`] = true,
    [`vacca`] = true,
    [`vader`] = false,
    [`vagner`] = true,
    [`vagrant`] = true,
    [`valkyrie`] = true,
    [`valkyrie2`] = true,
    [`vamos`] = false,
    [`vectre`] = true,
    [`velum`] = false,
    [`velum2`] = false,
    [`verlierer2`] = true,
    [`verus`] = true,
    [`vestra`] = true,
    [`vetir`] = false,
    [`veto`] = true,
    [`veto2`] = true,
    [`vigero`] = false,
    [`vigero2`] = true,
    [`vigilante`] = true,
    [`vindicator`] = true,
    [`virgo`] = false,
    [`virgo2`] = false,
    [`virgo3`] = false,
    [`viseris`] = false,
    [`visione`] = true,
    [`virtue`] = true,
    [`volatol`] = true,
    [`volatus`] = true,
    [`voltic`] = true,
    [`voltic2`] = true,
    [`voodoo`] = false,
    [`voodoo2`] = false,
    [`vortex`] = true,
    [`vstr`] = true,
    [`warrener`] = false,
    [`washington`] = true,
    [`wastelander`] = true,
    [`weevil`] = false,
    [`weevil2`] = true,
    [`windsor`] = true,
    [`windsor2`] = true,
    [`winky`] = false,
    [`wolfsbane`] = false,
    [`xa21`] = true,
    [`xls`] = true,
    [`xls2`] = true,
    [`yosemite`] = false,
    [`yosemite2`] = false,
    [`yosemite3`] = false,
    [`youga`] = true,
    [`youga2`] = false,
    [`youga3`] = true,
    [`youga4`] = false,
    [`z190`] = false,
    [`zeno`] = true,
    [`zentorno`] = true,
    [`zhaba`] = true,
    [`zion`] = true,
    [`zion2`] = true,
    [`zion3`] = false,
    [`zombiea`] = false,
    [`zombieb`] = false,
    [`zorrusso`] = true,
    [`zr350`] = true,
    [`zr380`] = true,
    [`zr3802`] = true,
    [`zr3803`] = true,
    [`ztype`] = false,
}

Config.BlacklistedWeapons = {
    [`WEAPON_RAILGUN`] = true,
}

Config.BlacklistedPeds = {
    [`s_m_y_ranger_01`] = true,
    [`s_m_y_sheriff_01`] = true,
    [`s_m_y_cop_01`] = true,
    [`s_f_y_sheriff_01`] = true,
    [`s_f_y_cop_01`] = true,
    [`s_m_y_hwaycop_01`] = true,
    [`a_m_y_acult_01`] = true,
    [`a_m_y_acult_02`] = true,
    [`a_f_y_fatcult_01`] = true,
    [`a_m_o_acult_01`] = true,
    [`a_m_o_acult_02`] = true,
    [`a_m_m_acult_01`] = true,
}

Config.WeapDraw = {
    variants = { 130, 122, 3, 6, 8 },
    weapons = {
        --'WEAPON_STUNGUN',
        'WEAPON_PISTOL',
        'WEAPON_PISTOL_MK2',
        'WEAPON_COMBATPISTOL',
        'WEAPON_APPISTOL',
        'WEAPON_PISTOL50',
        'WEAPON_REVOLVER',
        'WEAPON_SNSPISTOL',
        'WEAPON_HEAVYPISTOL',
        'WEAPON_VINTAGEPISTOL'
    }
}

Config.Objects = { -- for object removal
    { coords = vector3(266.09, -349.35, 44.74), heading = 0, length = 200, width = 200, model = 'prop_sec_barier_02b' },
    { coords = vector3(285.28, -355.78, 45.13), heading = 0, length = 200, width = 200, model = 'prop_sec_barier_02a' },
    {coords = vector3(847.3, -1299.98, 28.15), heading = 100.0, length = 200, width = 200, model = 'prop_monitor_01b'},
    {coords = vector3(370.66, -1593.19, 23.32), heading = 225.0, length = 200, width = 200, model = 'xm_prop_body_bag'},
    -- Unified Utilities chairs
    {coords = vector3(-52.09, -2523.71, 6.41), heading = 54.92, length = 5, width = 5, model = 'v_corp_cd_chair'},
    {coords = vector3(-59.63, -2517.78, 6.63), heading = 94.0, length = 5, width = 5, model = 'v_club_officechair'},
}

-- You may add more than 2 selections and it will bring up a menu for the player to select which floor be sure to label each section though
Config.Teleports = {
    [1] = {                   -- Elevator @ labs
        [1] = {               -- up
            poly = { coords = vector3(3540.74, 3675.59, 20.99), heading = 167.5, length = 2, width = 2 },
            allowVeh = false, -- whether or not to allow use in vehicle
            label = false     -- set this to a string for a custom label or leave it false to keep the default. if more than 2 options, label all options

        },
        [2] = { -- down
            poly = { coords = vector3(3540.74, 3675.59, 28.11), heading = 172.5, length = 2, width = 2 },
            allowVeh = false,
            label = false
        }
    },
    [2] = { --Coke Processing Enter/Exit
        [1] = {
            poly = { coords = vector3(909.49, -1589.22, 30.51), heading = 92.24, length = 2, width = 2 },
            allowVeh = false,
            label = '[E] Enter Coke Processing'
        },
        [2] = {
            poly = { coords = vector3(1088.81, -3187.57, -38.99), heading = 181.7, length = 2, width = 2 },
            allowVeh = false,
            label = '[E] Leave'
        }
    }
}

Config.CarWash = {
    dirtLevel = 0.1,                                                                                   -- threshold for the dirt level to be counted as dirty
    defaultPrice = 20,                                                                                 -- default price for the carwash
    locations = {
        [1] = { coords = vector3(174.81, -1736.77, 28.87), length = 7.0, width = 8.8, heading = 359 }, -- South Los Santos Carson Avenue
        [2] = { coords = vector3(25.2, -1391.98, 28.91), length = 6.6, width = 8.2, heading = 0 },     -- South Los Santos Innocence Boulevard
        [3] = { coords = vector3(-74.27, 6427.72, 31.02), length = 9.4, width = 8, heading = 315 },    -- Paleto Bay Boulevard
        [4] = { coords = vector3(1362.69, 3591.81, 34.5), length = 6.4, width = 8, heading = 21 },     -- Sandy Shores
        [5] = { coords = vector3(-699.84, -932.68, 18.59), length = 11.8, width = 5.2, heading = 0 }   -- Little Seoul Gas Station
    }
}
